# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dil', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='messages',
            new_name='Message',
        ),
        migrations.RenameModel(
            old_name='UserDetails',
            new_name='UserDetail',
        ),
    ]
