# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dil', '0002_auto_20170401_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='dob',
            field=models.DateField(verbose_name='Date Of Birth'),
        ),
    ]
