# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dil', '0007_yellowroserecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sent_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
